# 创建pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-nfs-pvc
  namespace: default
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
# 部署 deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.6
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: redis-pvc
          mountPath: "/data"
        command:
          - "redis-server"
      volumes:
      - name: redis-pvc
        persistentVolumeClaim:
          claimName: redis-nfs-pvc
# 创建Service
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels: 
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector: 
    app: redis
