apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-nfs-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # storage: 1Gi
      storage: 20Gi
